FROM ubuntu:bionic
MAINTAINER 9JKH Dev<dev@9jkh.co.za>

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update -qq && apt-get install -y -qq \
  build-essential \
  devscripts \
  equivs \
  libwww-perl \
  curl
